<div class="blog-entry">
    <p class="date-title"><?= $entry['date'] ?> : <?= $entry['title'] ?></p>
    <p class="content"><?= $entry['content']?></p>
    <p class="author">Nickname 1</p>

    <div class="commentSection">
        <p><u>1 Kommentar vorhanden :</u></p>
        <div class="comment">
            <p>1. <strong>Max</strong>(verlinkt auf die eingegebene URL) meint: (06.10.2006 um 12:34):
            <p> Ich denke der Eintrag ist sehr gut, weiter so!</p>
        </div>
    </div>

    <p><u>Kommentar schreiben :</u></p>
    <form  method="POST" action="" class="dummyFormComment">
        <div class="form-item">
            <label for="name"><b>Name</b></label>
            <input type="text" name="name" required>
        </div>
        <div class="form-item">
            <label for="mail"><b>Mail (optional)</b></label>
            <input type="password" name="mail">
        </div>
        <div class="form-item">
            <label for="url"><b>URL (optional)</b></label>
            <input type="text" name="mail">
        </div>
        <div class="form-item">
            <label for="comment"><b>Bemerkung</b></label>
            <textarea cols="20"></textarea>
        </div>
        <button type="submit" name="sendComment" id="sendComment">Absenden</button>
    </form>
</div>

