<div class="container">
    <form class="form" method="POST" action="">
        <h2>Login Form</h2>
        <label for="username"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="username" required>

        <label for="password"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="password" required>
        <?php if(!empty($errorMessage)) : ?>
            <div class="error"><?= $errorMessage?></div>
        <?php endif; ?>
        <button  class="button" type="submit" name="login" value="login">Login</button>
        <label>
            <input type="checkbox" checked="checked" name="remember"> Remember me
        </label>
    </form>
</div>

