<div class="container">
    <?php foreach ($blogEntries as $i => $blogEntry) : ?>
        <div class="blog-entry">
            <p class="date-title"><?= $blogEntry['date'] == date('Y.m.d') ?  .': '?><a href="/Details-Page?id=<?= $blogEntry['ID'] ?>"><?= $blogEntry['title'] ?></a></p>
            <p class="content"><?= strlen($blogEntry['content']) > 1000 ? substr($blogEntry['Text'],0,1000)."<a href='/Details-Page'> [...]</a>" : $blogEntry['content']?></p>
            <p class="author"><?= $blogEntry['author']?><a href="/Details-Page">Comments <!-- <?= count($blogEntry['Comments'])//ToDo Display author name and comment number ?> --></a></p>
        </div>
    <?php endforeach; ?>

    <?php if (!$lastPage) : ?>
    <form action="" method="POST" class="form">
        <button class="button" type="submit" name="page" value="next">Ältere Einträge</button>
    </form>
    <?php else : ?>
    <form action="" method="POST" class="form">
        <button class="button" type="submit" name="latestEntries" value="1">Zurück zum Anfang</button>
    </form>
    <?php endif; ?>

</div>

