<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>Home</title>
    <link rel="stylesheet" href="css/main.css"/>
    <link rel="stylesheet" href="css/login-form.css">
</head>
<body>
    <div class="header">
        <a href="/"><img src="images/banner-blue.jpg" alt="a blue banner"></a>
    </div>

    <div class="navbar">
        <a href="/">Startseite</a>
        <?php if(!isset($_SESSION['validity'])) : ?>
        <a href="/Login-Form">Login</a>
        <?php else : ?>
            <a href="/Add-Entry">Eintrag hinzufügen</a>
            <a href=<?= '/?Logout='.true ?>>Logout</a>
        <?php endif; ?>
    </div>

    <?= $templateOutput ?>

    <div class="footer">
        <p>&copy; 2018 - <a href="/Impressum">Impressum</a></p>
    </div>
</body>
</html>